-- 001_initial_schema.sql
-- Run this in your Supabase SQL Editor to initialize the database for Spider-Verse Quest Engine

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- USERS Table
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT,
  xp BIGINT DEFAULT 0,
  level INTEGER DEFAULT 1,
  streak INTEGER DEFAULT 0,
  longest_streak INTEGER DEFAULT 0,
  last_active DATE,
  spider_sense_domains JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- QUESTS Table
CREATE TABLE IF NOT EXISTS public.quests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  domain TEXT NOT NULL,
  topic TEXT NOT NULL,
  source TEXT NOT NULL,
  xp_reward INTEGER NOT NULL,
  completed SMALLINT DEFAULT 0,
  completed_at TIMESTAMPTZ,
  quest_date DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- SKILLS Table
CREATE TABLE IF NOT EXISTS public.skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  domain TEXT NOT NULL,
  xp BIGINT DEFAULT 0,
  quest_count INTEGER DEFAULT 0,
  color TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, name)
);

-- ACHIEVEMENTS Table
CREATE TABLE IF NOT EXISTS public.achievements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  icon TEXT NOT NULL,
  category TEXT NOT NULL,
  unlocked_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, name)
);

-- TOPIC HISTORY Table
CREATE TABLE IF NOT EXISTS public.topic_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  topic TEXT NOT NULL,
  domain TEXT NOT NULL,
  used_at TIMESTAMPTZ DEFAULT NOW()
);

-- RANDOM EVENTS Table
CREATE TABLE IF NOT EXISTS public.random_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  xp_modifier REAL DEFAULT 1.0,
  active SMALLINT DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- IN DEXES
CREATE INDEX IF NOT EXISTS idx_quests_user_date ON public.quests(user_id, quest_date);
CREATE INDEX IF NOT EXISTS idx_topic_history_user ON public.topic_history(user_id, used_at);
CREATE INDEX IF NOT EXISTS idx_skills_user ON public.skills(user_id);

-- Set up Row Level Security (RLS)
-- Since the backend acts as the authoritative source and uses the Service Role Key, 
-- we can enable RLS and leave the tables protected from direct anonymous client access.
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.topic_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.random_events ENABLE ROW LEVEL SECURITY;
